apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "hangat.fullname" . }}-backend-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hangat.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend

data:
  {{- range $key, $value := .Values.backend.configEnv }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}