{{- if .Values.ingress.enabled }}

apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: {{ include "hangat.fullname" . }}-api
  namespace: {{ .Release.Namespace }}

  labels:
    {{- include "hangat.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend

  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ingress.api.proxyBodySize | quote }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: {{ .Values.ingress.api.proxyReadTimeout | quote }}
    nginx.ingress.kubernetes.io/proxy-send-timeout: {{ .Values.ingress.api.proxySendTimeout | quote }}
    nginx.ingress.kubernetes.io/proxy-buffering: "off"

    nginx.ingress.kubernetes.io/ssl-redirect: {{ .Values.ingress.forceSslRedirect | quote }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: {{ .Values.ingress.forceSslRedirect | quote }}

spec:
  ingressClassName: {{ .Values.ingress.className }}

  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.api.host | quote }}

      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}

  rules:
    - host: {{ .Values.ingress.api.host | quote }}

      http:
        paths:
          - path: /
            pathType: Prefix

            backend:
              service:
                name: {{ include "hangat.fullname" . }}-backend

                port:
                  number: {{ .Values.backend.service.port }}

{{- end }}